type = "webpack"
account_id = ""
zone_id = "9258b29d3b22bdba0666469e82d18225"
workers_dev = true
compatibility_date = "2021-10-23"

[env.development]
name = "solidhack-dev"
route = "dev-hack.solidjs.com/*"

[env.production]
name = "solidhack"
route = "hack.solidjs.com/*"

[site]
bucket = "./dist"
entry-point = "workers-site"
